# Generated by Django 5.0.3 on 2024-05-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type_choice',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used'), ('Academic', 'Academic'), ('Admission', 'Admission')], max_length=100, null=True),
        ),
    ]
