# Generated by Django 4.2.19 on 2025-02-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_book_type_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="review_choice",
        ),
        migrations.RemoveField(
            model_name="order",
            name="accessories",
        ),
        migrations.RemoveField(
            model_name="order",
            name="book",
        ),
        migrations.RemoveField(
            model_name="order",
            name="ebook",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="review",
            name="Book",
        ),
        migrations.RemoveField(
            model_name="review",
            name="acc",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.DeleteModel(
            name="Accessories",
        ),
        migrations.DeleteModel(
            name="book",
        ),
        migrations.DeleteModel(
            name="ebook",
        ),
        migrations.DeleteModel(
            name="order",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
