# Generated by Django 4.2.19 on 2025-02-25 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "products",
            "0003_remove_book_review_choice_remove_order_accessories_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="images/default.jpg",
                        null=True,
                        upload_to="images/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("publisher", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Story", "Story"),
                            ("Fiction", "Fiction"),
                            ("Non-Fiction", "Non-Fiction"),
                            ("Novel", "Novel"),
                            ("History", "History"),
                            ("Poetry", "Poetry"),
                            ("Cookbook", "Cookbook"),
                            ("Drama", "Drama"),
                            ("Thriller", "Thriller"),
                            ("Biography", "Biography"),
                            ("Action", "Action"),
                            ("Literature", "Literature"),
                            ("Adventure", "Adventure"),
                            ("Others", "Others"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("price", models.IntegerField(blank=True, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="images/default.jpg",
                        null=True,
                        upload_to="images/",
                    ),
                ),
                (
                    "type_choice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("New", "New"),
                            ("Used", "Used"),
                            ("Academic", "Academic"),
                            ("Admission", "Admission"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="images/default.jpg",
                        null=True,
                        upload_to="images/",
                    ),
                ),
                ("price", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_choice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "Book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.book",
                    ),
                ),
                (
                    "acc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.accessories",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="review_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.review",
            ),
        ),
        migrations.AddField(
            model_name="accessories",
            name="review_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.review",
            ),
        ),
    ]
