# Generated by Django 4.2.19 on 2025-04-11 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0009_ebook_donated_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ebook",
            name="donated_by",
        ),
        migrations.AddField(
            model_name="accessories",
            name="donated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
