# Generated by Django 4.2.19 on 2025-04-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_remove_ebook_donated_by_accessories_donated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
