# Generated by Django 4.2.19 on 2025-04-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_book_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessories",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ebook",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
