# Generated by Django 4.2.19 on 2025-04-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_accessories_date_time_ebook_date_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessories",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="accessories",
            name="sales_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="book",
            name="sales_count",
            field=models.IntegerField(default=0),
        ),
    ]
