# Generated by Django 4.2.19 on 2025-05-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0013_accessories_average_rating_accessories_sales_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("delivered", "Delivered")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
